### PR TITLE
Release v4.0.0

### PR DESCRIPTION
**Pull request by wroyca**
Hey @Rookfighter, you always deliver when it matters! Just as I was about to tackle the task of packaging FTXUI, I discovered on cppget that you had already handled it. I'm extremely grateful for that! Additionally, v4.0.0 was recently released, so this pull request updates the package accordingly. Please note that the [Bdep CI](https://ci.stage.build2.org/@c632cac3-b902-40c5-94bb-eccf06bfadf0) fails due to a failure to initialize the packages in the build configurations. It's a bit confusing, so I'm not quite sure what's happening there. Nevertheless, the tests pass correctly on my system, so I'll leave that matter in your hands—Again, thank for the package! 

image

### CODE REVIEW

**Comment by Rookfighter** [comment]
Cheers @wroyca,
thanks for your PR and the update :+1: Your changes look good so far, I'll quickly check on the bdep CI errors.

**Comment by Rookfighter** [comment]
There were a few new examples added in 4.0.0

```
A	examples/component/custom_loop.cpp
A	examples/component/focus_cursor.cpp
A	examples/component/modal_dialog_custom.cpp
A	examples/component/slider_direction.cpp
A	examples/dom/style_strikethrough.cpp
A	examples/dom/style_underlined_double.cpp
```

You could add them at your choice (don't forget to update the .gitignore for the executeables). I won't block the PR if you do not want to add them.

@boris-kolpackov could you give us a hint on the bdep CI error? It seems like `libftxui-tests` is not able to resolve its dependency to `libftxui`. I believe the dependency should be implicitly given because `libftxui` declares `tests: libftxui-tests` in its manifest.
As @wroyca mentioned it works locally (also for me). I cannot really figure out how to reproduce the bdep ci steps locally. Any ideas?

**Comment by wroyca** [comment]
Thank, I missed those, will update later today-

**Comment by wroyca** [comment]
@Rookfighter, done. Thank you for bringing this to my attention!

**Comment by boris-kolpackov** [comment]
> could you give us a hint on the bdep CI error? It seems like `libftxui-tests` is not able to resolve its dependency to `libftxui`.

Hm, don't see anything immediately obvious. Does the master branch CI successfully on stage? If it also fails, might be worth to try to CI it on ci.cppget.org, see if we maybe broke something on stage.

**Comment by Rookfighter** [comment]
@boris-kolpackov 

So here's the bdep ci build of `3.0.0+1` from the original repo's master branch. Same error.

**3.0.0+1:** https://ci.stage.build2.org/@8168f477-99b4-4d68-9a37-9cb0e3941031

For comparison here is the build of `4.0.0` from @wroyca repo's master branch:

**4.0.0:** https://ci.stage.build2.org/@eb96213b-5824-4967-950b-79d9e2fe9fb1

Here's a  build on ci.cppget.org with @wroyca `4.0.0`, which actually succeeds with warnings. I used the command `bdep ci --server https://ci.cppget.org`.

**4.0.0:** https://ci.cppget.org/@303e7f1b-3b2c-428c-a6ba-03d7d04bcbbd

Seems like there is some difference between `build2` 0.15.0 and the stage version. Any ideas?

**Comment by boris-kolpackov** [comment]
@Rookfighter Thanks for the detective work. Will investigate the reason for the difference and get back.

**Comment by boris-kolpackov** [comment]
Ok, this turned out to be a bug in `build2` (specifically, in `bpkg`, introduced as part of the in-process configure optimization work: https://github.com/build2/build2/issues/271).

This has now been fixed in the latest staged toolchain and I expect stage CI behavior to be the same as public now (but let me know if there are still any discrepancies). Thanks for detecting this bug and helping track it down!

**Comment by Rookfighter** [comment]
@boris-kolpackov Thanks, great that you already solved it. I will then proceed and merge this PR :+1:

**Pull request merged**
